repository: sproogen/resume-theme 
favicon: images/favicon.ico 

version: 2

name: Muhammad Aamir Saeed
title: Platform Engineer
location: Milton Keynes, England
email: m.aamir.s.110@gmail.com
website: www.linkedin.com/in/maamirs

darkmode: true

github_username: maamirs
linkedin_username: maamirs

additional_links:

about_profile_image: images/profile.jpg
about_content: |
  Platform Engineer with experience developing and maintaining backend infrastructure, ensuring performance, reliability, and scalability. Proficient in designing and implementing CI/CD pipelines (Azure DevOps, AWS CodeBuild), managing containerized applications (Kubernetes, Docker), and utilizing cloud services (AWS, Azure). Skilled in Infrastructure as Code (Terraform, Ansible, CloudFormation, ARM) and monitoring (CloudWatch, Azure Monitor, Prometheus, Grafana). AWS Certified Solutions Architect with deep expertise in cloud architecture and best practices. Also experienced in Embedded Software Engineering (C++, C, Python, Yocto, RTOS).

  Key skills include: <mark>AWS</mark>, <mark>Azure DevOps</mark>, <mark>Kubernetes</mark>, <mark>Terraform</mark>, <mark>CI/CD</mark>, <mark>C/C++</mark>, <mark>Embedded Linux</mark>. 

content:
  # - title: Projects
  #   layout: list
  #   content:
  #     - layout: top-middle
  #       title: Processor Design for Graph Applications
  #       additional_links:
  #         - title: IEEE 2022 30th Signal Processing and Communications Applications Conference
  #           icon: fas fa-book
  #           url:
  #       quote: >
  #         Publication based on Master's research.
  #       description: |
  #         Developed as part of the Master's program at Bilkent University. Analysis of Scratch Pad Memory-based Processor Architecture for Graph Parallel Applications.

  #     - layout: top-middle
  #       title: Secure Communication System for SUPARCO
  #       quote: >
  #         Final Year Project for Bachelor's degree.
  #       description: |
  #         Development of Secure and Reliable Communication System for SUPARCO (Pakistan) for B.Sc. at COMSATS University.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: BP (British Petroleum)
        sub_title: Platform Engineer
        caption: March 202 – Present
        description: |
            Develop and maintain backend infrastructure for the BP Pulse app, ensuring performance, reliability, and scalability.
            Design and implement CI/CD pipelines using Azure DevOps Pipelines and AWS CodeBuild, enabling efficient software delivery and automated deployments.
            Manage and optimize containerized applications using Kubernetes (Amazon EKS) and Docker, ensuring seamless orchestration and scalability.
            Utilize AWS services (EC2, S3, RDS, Lambda, DynamoDB, CloudFormation) and Azure DevOps to build and deploy scalable cloud solutions.
            Automate infrastructure provisioning and configuration management with Terraform, Ansible, CloudFormation, and Azure Resource Manager (ARM) templates.
            Implement monitoring and observability using AWS CloudWatch, Azure Monitor, Prometheus, and Grafana, ensuring system reliability and proactive incident resolution.

      - layout: left
        title: BP (British Petroleum)
        sub_title: Embedded Software Engineer
        caption: October 2022 – February 2024
        description: |
            Develop and design next-gen embedded software (C++/C) for electric car chargers (IEC 61851, OCPP 1.6 & 2.0.1, MISRA, UK smart charge standards). Design Windows-based simulator for charge points. Develop/build embedded Linux (Yocto) for SoCs. Maintain legacy Python code. Create/Maintain CI/CD pipelines (Azure ADO, AWS). Provide customer support for bugs.

      - layout: left
        title: Baykar Tech
        sub_title: Embedded Software Engineer
        caption: April 2021 – October 2022
        description: |
            Spearheaded multi-threaded C/C++ scalable applications on Embedded ARM SoCs. Managed/built Real-time Linux (RTOS) kernel builds and C device drivers. Developed FPGA IPs and device drivers for ARM SoCs (GNSS, Ethernet). Maintained embedded Linux bootloaders and device trees. Performed integration testing for UAV applications. Designed/simulated MATLAB Simulink models for 5G signal processing.

      - layout: left
        title: Bilkent University
        sub_title: Graduate Teaching Assistant
        caption: September 2018 – April 2021
        description: |
            Provided instructional support, formulated lesson plans. Trained undergraduate students on FPGA development and digital design systems (System Verilog/Verilog). Instructed weekly labs and tutorials.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Bilkent University, Ankara, Turkey
        caption: 2021
        sub_title: Master of Science in Computer Engineering
        description: |
          Publication: Processor Design for Graph Applications – [IEEE 2022 30th Signal Processing and Communications Applications Conference](https://ieeexplore.ieee.org/document/9864699), 
          Awards/Honours: Departmental Scholarship, TÜBİTAK Sponsored Project (Grant no: EEEAG 119E559).
          Research Thesis: “Analysis of Scratch Pad Memory-based Processor Architecture for Graph Parallel Applications.” [Bilkent University Repository](https://repository.bilkent.edu.tr/items/ee6d144f-9d8f-49b4-a4d1-ba2aa8b28e7b).

      - layout: left
        title: COMSATS University, Islamabad, Pakistan
        caption: 2018
        sub_title: Bachelor of Science in Electrical (Computer) Engineering
        description: |
          GPA: 3.43/4.00.
          Awards/Honours: Two Distinctions, Honour Roll.
          Final Year Project: “Development of Secure and Reliable Communication System for SUPARCO (Pakistan).”

footer_show_references: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
